// frontends/src/components/OverviewPanel.vue
<script setup lang="ts">
defineProps<{
  title: string;
  value: string;
  description: string;
}>();
</script>

<template>
  <div class="panel">
    <h2 class="panel-title">{{ title }}</h2>
    <div class="panel-value">{{ value }}</div>
    <div class="panel-desc">{{ description }}</div>
  </div>
</template>

// frontend/src/components/OverviewPanel.tsx
type OverviewPanelProps = {
  title: string;
  value: string;
  description: string;
};

export function OverviewPanel({ title, value, description }: OverviewPanelProps) {
  return (
    <section className="panel">
      <h3>{title}</h3>
      <p className="metric">{value}</p>
      <small>{description}</small>
    </section>
  );
}
